### ISSUE TITLE
Syntax Error in node_modules

### ISSUE THREAD

**Issue by geoffdavis92** [Polymer/polymer-element-catalog#162]
I'm having a terrible time trying to get every piece of the Docs dependency process working, and 

So I'm trying to run `$ npm run serve`, and I'm getting the following error message as it tries to execute the Gulp task: 
```commandline
polymer-element-catalog <MyUserName>$ gulp
/Users/<MyUserName>/github/polymer-local-docs/docs/polymer-element-catalog/node_modules/browser-sync/<MyUserName>/dev-ip/node_modules/lodash/dist/lodash.js:2840
});
^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/<MyUserName>/github/polymer-local-docs/docs/polymer-element-catalog/node_modules/browser-sync/node_modules/dev-ip/lib/dev-ip.js:13:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

It looks like it's throwing an error from deep within dependencies of dependencies; not sure how it found its way to my machine and/or if anyone else has this problem, but I'm not sure how to go forward.

I did try to manually edit it and still didn't work.

Thanks!

**Comment by samccone** [comment]
hey @geoffdavis92 mind deleting you node_modules folder and `npm i` again off of master. I just tried this and things seem to be ok

**Comment by ebidel** [comment]
This issue has gone stale. If you still are seeing issues, please reopen.
